# encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Language.create english_name: "Abkhaz", native_name: "аҧсуа бызшәа, аҧсшәа", code: "ab"
Language.create english_name: "Afar", native_name: "Afaraf", code: "aa"
Language.create english_name: "Afrikaans", native_name: "Afrikaans", code: "af"
Language.create english_name: "Akan", native_name: "Akan", code: "ak"
Language.create english_name: "Albanian", native_name: "gjuha shqipe", code: "sq"
Language.create english_name: "Amharic", native_name: "አማርኛ", code: "am"
Language.create english_name: "Arabic", native_name: "العربية", code: "ar"
Language.create english_name: "Aragonese", native_name: "aragonés", code: "an"
Language.create english_name: "Armenian", native_name: "Հայերեն", code: "hy"
Language.create english_name: "Assamese", native_name: "অসমীয়া", code: "as"
Language.create english_name: "Avaric", native_name: "авар мацӀ, магӀарул мацӀ", code: "av"
Language.create english_name: "Avestan", native_name: "avesta", code: "ae"
Language.create english_name: "Aymara", native_name: "aymar aru", code: "ay"
Language.create english_name: "Azerbaijani", native_name: "azərbaycan dili", code: "az"
Language.create english_name: "Bambara", native_name: "bamanankan", code: "bm"
Language.create english_name: "Bashkir", native_name: "башҡорт теле", code: "ba"
Language.create english_name: "Basque", native_name: "euskara, euskera", code: "eu"
Language.create english_name: "Belarusian", native_name: "беларуская мова", code: "be"
Language.create english_name: "Bengali; Bangla", native_name: "বাংলা", code: "bn"
Language.create english_name: "Bihari", native_name: "भोजपुरी", code: "bh"
Language.create english_name: "Bislama", native_name: "Bislama", code: "bi"
Language.create english_name: "Bosnian", native_name: "bosanski jezik", code: "bs"
Language.create english_name: "Breton", native_name: "brezhoneg", code: "br"
Language.create english_name: "Bulgarian", native_name: "български език", code: "bg"
Language.create english_name: "Burmese", native_name: "ဗမာစာ", code: "my"
Language.create english_name: "Catalan; Valencian", native_name: "català, valencià", code: "ca"
Language.create english_name: "Chamorro", native_name: "Chamoru", code: "ch"
Language.create english_name: "Chechen", native_name: "нохчийн мотт", code: "ce"
Language.create english_name: "Chichewa; Chewa; Nyanja", native_name: "chiCheŵa, chinyanja", code: "ny"
Language.create english_name: "Chinese", native_name: "中文 (Zhōngwén), 汉语, 漢語", code: "zh"
Language.create english_name: "Chuvash", native_name: "чӑваш чӗлхи", code: "cv"
Language.create english_name: "Cornish", native_name: "Kernewek", code: "kw"
Language.create english_name: "Corsican", native_name: "corsu, lingua corsa", code: "co"
Language.create english_name: "Cree", native_name: "ᓀᐦᐃᔭᐍᐏᐣ", code: "cr"
Language.create english_name: "Croatian", native_name: "hrvatski jezik", code: "hr"
Language.create english_name: "Czech", native_name: "čeština, český jazyk", code: "cs"
Language.create english_name: "Danish", native_name: "dansk", code: "da"
Language.create english_name: "Divehi; Dhivehi; Maldivian;", native_name: "ދިވެހި", code: "dv"
Language.create english_name: "Dutch", native_name: "Nederlands, Vlaams", code: "nl"
Language.create english_name: "Dzongkha", native_name: "རྫོང་ཁ", code: "dz"
Language.create english_name: "English", native_name: "English", code: "en"
Language.create english_name: "Esperanto", native_name: "Esperanto", code: "eo"
Language.create english_name: "Estonian", native_name: "eesti, eesti keel", code: "et"
Language.create english_name: "Ewe", native_name: "Eʋegbe", code: "ee"
Language.create english_name: "Faroese", native_name: "føroyskt", code: "fo"
Language.create english_name: "Fijian", native_name: "vosa Vakaviti", code: "fj"
Language.create english_name: "Finnish", native_name: "suomi, suomen kieli", code: "fi"
Language.create english_name: "French", native_name: "français, langue française", code: "fr"
Language.create english_name: "Fula; Fulah; Pulaar; Pular", native_name: "Fulfulde, Pulaar, Pular", code: "ff"
Language.create english_name: "Galician", native_name: "galego", code: "gl"
Language.create english_name: "Georgian", native_name: "ქართული", code: "ka"
Language.create english_name: "German", native_name: "Deutsch", code: "de"
Language.create english_name: "Greek, Modern", native_name: "ελληνικά", code: "el"
Language.create english_name: "Guaraní", native_name: "Avañe'ẽ", code: "gn"
Language.create english_name: "Gujarati", native_name: "ગુજરાતી", code: "gu"
Language.create english_name: "Haitian; Haitian Creole", native_name: "Kreyòl ayisyen", code: "ht"
Language.create english_name: "Hausa", native_name: "Hausa, هَوُسَ", code: "ha"
Language.create english_name: "Hebrew (modern)", native_name: "עברית", code: "he"
Language.create english_name: "Herero", native_name: "Otjiherero", code: "hz"
Language.create english_name: "Hindi", native_name: "हिन्दी, हिंदी", code: "hi"
Language.create english_name: "Hiri Motu", native_name: "Hiri Motu", code: "ho"
Language.create english_name: "Hungarian", native_name: "magyar", code: "hu"
Language.create english_name: "Interlingua", native_name: "Interlingua", code: "ia"
Language.create english_name: "Indonesian", native_name: "Bahasa Indonesia", code: "id"
Language.create english_name: "Interlingue", native_name: "Originally called Occidental; then Interlingue after WWII", code: "ie"
Language.create english_name: "Irish", native_name: "Gaeilge", code: "ga"
Language.create english_name: "Igbo", native_name: "Asụsụ Igbo", code: "ig"
Language.create english_name: "Inupiaq", native_name: "Iñupiaq, Iñupiatun", code: "ik"
Language.create english_name: "Ido", native_name: "Ido", code: "io"
Language.create english_name: "Icelandic", native_name: "Íslenska", code: "is"
Language.create english_name: "Italian", native_name: "italiano", code: "it"
Language.create english_name: "Inuktitut", native_name: "ᐃᓄᒃᑎᑐᑦ", code: "iu"
Language.create english_name: "Japanese", native_name: "日本語 (にほんご)", code: "ja"
Language.create english_name: "Javanese", native_name: "basa Jawa", code: "jv"
Language.create english_name: "Kalaallisut, Greenlandic", native_name: "kalaallisut, kalaallit oqaasii", code: "kl"
Language.create english_name: "Kannada", native_name: "ಕನ್ನಡ", code: "kn"
Language.create english_name: "Kanuri", native_name: "Kanuri", code: "kr"
Language.create english_name: "Kashmiri", native_name: "कश्मीरी, كشميري‎", code: "ks"
Language.create english_name: "Kazakh", native_name: "қазақ тілі", code: "kk"
Language.create english_name: "Khmer", native_name: "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ", code: "km"
Language.create english_name: "Kikuyu, Gikuyu", native_name: "Gĩkũyũ", code: "ki"
Language.create english_name: "Kinyarwanda", native_name: "Ikinyarwanda", code: "rw"
Language.create english_name: "Kyrgyz", native_name: "Кыргызча, Кыргыз тили", code: "ky"
Language.create english_name: "Komi", native_name: "коми кыв", code: "kv"
Language.create english_name: "Kongo", native_name: "KiKongo", code: "kg"
Language.create english_name: "Korean", native_name: "한국어 (韓國語), 조선어 (朝鮮語)", code: "ko"
Language.create english_name: "Kurdish", native_name: "Kurdî, كوردی‎", code: "ku"
Language.create english_name: "Kwanyama, Kuanyama", native_name: "Kuanyama", code: "kj"
Language.create english_name: "Latin", native_name: "latine, lingua latina", code: "la"
Language.create english_name: "Luxembourgish, Letzeburgesch", native_name: "Lëtzebuergesch", code: "lb"
Language.create english_name: "Ganda", native_name: "Luganda", code: "lg"
Language.create english_name: "Limburgish, Limburgan, Limburger", native_name: "Limburgs", code: "li"
Language.create english_name: "Lingala", native_name: "Lingála", code: "ln"
Language.create english_name: "Lao", native_name: "ພາສາລາວ", code: "lo"
Language.create english_name: "Lithuanian", native_name: "lietuvių kalba", code: "lt"
Language.create english_name: "Luba-Katanga", native_name: "Tshiluba", code: "lu"
Language.create english_name: "Latvian", native_name: "latviešu valoda", code: "lv"
Language.create english_name: "Manx", native_name: "Gaelg, Gailck", code: "gv"
Language.create english_name: "Macedonian", native_name: "македонски јазик", code: "mk"
Language.create english_name: "Malagasy", native_name: "fiteny malagasy", code: "mg"
Language.create english_name: "Malay", native_name: "bahasa Melayu, بهاس ملايو‎", code: "ms"
Language.create english_name: "Malayalam", native_name: "മലയാളം", code: "ml"
Language.create english_name: "Maltese", native_name: "Malti", code: "mt"
Language.create english_name: "Māori", native_name: "te reo Māori", code: "mi"
Language.create english_name: "Marathi (Marāṭhī)", native_name: "मराठी", code: "mr"
Language.create english_name: "Marshallese", native_name: "Kajin M̧ajeļ", code: "mh"
Language.create english_name: "Mongolian", native_name: "монгол", code: "mn"
Language.create english_name: "Nauru", native_name: "Ekakairũ Naoero", code: "na"
Language.create english_name: "Navajo, Navaho", native_name: "Diné bizaad, Dinékʼehǰí", code: "nv"
Language.create english_name: "Norwegian Bokmål", native_name: "Norsk bokmål", code: "nb"
Language.create english_name: "North Ndebele", native_name: "isiNdebele", code: "nd"
Language.create english_name: "Nepali", native_name: "नेपाली", code: "ne"
Language.create english_name: "Ndonga", native_name: "Owambo", code: "ng"
Language.create english_name: "Norwegian Nynorsk", native_name: "Norsk nynorsk", code: "nn"
Language.create english_name: "Norwegian", native_name: "Norsk", code: "no"
Language.create english_name: "Nuosu", native_name: "ꆈꌠ꒿ Nuosuhxop", code: "ii"
Language.create english_name: "South Ndebele", native_name: "isiNdebele", code: "nr"
Language.create english_name: "Occitan", native_name: "occitan, lenga d'òc", code: "oc"
Language.create english_name: "Ojibwe, Ojibwa", native_name: "ᐊᓂᔑᓈᐯᒧᐎᓐ", code: "oj"
Language.create english_name: "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", native_name: "ѩзыкъ словѣньскъ", code: "cu"
Language.create english_name: "Oromo", native_name: "Afaan Oromoo", code: "om"
Language.create english_name: "Oriya", native_name: "ଓଡ଼ିଆ", code: "or"
Language.create english_name: "Ossetian, Ossetic", native_name: "ирон æвзаг", code: "os"
Language.create english_name: "Panjabi, Punjabi", native_name: "ਪੰਜਾਬੀ, پنجابی‎", code: "pa"
Language.create english_name: "Pāli", native_name: "पाऴि", code: "pi"
Language.create english_name: "Persian", native_name: "فارسی", code: "fa"
Language.create english_name: "Polish", native_name: "język polski, polszczyzna", code: "pl"
Language.create english_name: "Pashto, Pushto", native_name: "پښتو", code: "ps"
Language.create english_name: "Portuguese", native_name: "português", code: "pt"
Language.create english_name: "Quechua", native_name: "Runa Simi, Kichwa", code: "qu"
Language.create english_name: "Romansh", native_name: "rumantsch grischun", code: "rm"
Language.create english_name: "Kirundi", native_name: "Ikirundi", code: "rn"
Language.create english_name: "Romanian, Moldavian(Romanian from Republic of Moldova)", native_name: "limba română", code: "ro"
Language.create english_name: "Russian", native_name: "русский язык", code: "ru"
Language.create english_name: "Sanskrit (Saṁskṛta)", native_name: "संस्कृतम्", code: "sa"
Language.create english_name: "Sardinian", native_name: "sardu", code: "sc"
Language.create english_name: "Sindhi", native_name: "सिन्धी, سنڌي، سندھی‎", code: "sd"
Language.create english_name: "Northern Sami", native_name: "Davvisámegiella", code: "se"
Language.create english_name: "Samoan", native_name: "gagana fa'a Samoa", code: "sm"
Language.create english_name: "Sango", native_name: "yângâ tî sängö", code: "sg"
Language.create english_name: "Serbian", native_name: "српски језик", code: "sr"
Language.create english_name: "Scottish Gaelic; Gaelic", native_name: "Gàidhlig", code: "gd"
Language.create english_name: "Shona", native_name: "chiShona", code: "sn"
Language.create english_name: "Sinhala, Sinhalese", native_name: "සිංහල", code: "si"
Language.create english_name: "Slovak", native_name: "slovenčina, slovenský jazyk", code: "sk"
Language.create english_name: "Slovene", native_name: "slovenski jezik, slovenščina", code: "sl"
Language.create english_name: "Somali", native_name: "Soomaaliga, af Soomaali", code: "so"
Language.create english_name: "Southern Sotho", native_name: "Sesotho", code: "st"
Language.create english_name: "Spanish; Castilian", native_name: "español, castellano", code: "es"
Language.create english_name: "Sundanese", native_name: "Basa Sunda", code: "su"
Language.create english_name: "Swahili", native_name: "Kiswahili", code: "sw"
Language.create english_name: "Swati", native_name: "SiSwati", code: "ss"
Language.create english_name: "Swedish", native_name: "Svenska", code: "sv"
Language.create english_name: "Tamil", native_name: "தமிழ்", code: "ta"
Language.create english_name: "Telugu", native_name: "తెలుగు", code: "te"
Language.create english_name: "Tajik", native_name: "тоҷикӣ, toğikī, تاجیکی‎", code: "tg"
Language.create english_name: "Thai", native_name: "ไทย", code: "th"
Language.create english_name: "Tigrinya", native_name: "ትግርኛ", code: "ti"
Language.create english_name: "Tibetan Standard, Tibetan, Central", native_name: "བོད་ཡིག", code: "bo"
Language.create english_name: "Turkmen", native_name: "Türkmen, Түркмен", code: "tk"
Language.create english_name: "Tagalog", native_name: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔", code: "tl"
Language.create english_name: "Tswana", native_name: "Setswana", code: "tn"
Language.create english_name: "Tonga (Tonga Islands)", native_name: "faka Tonga", code: "to"
Language.create english_name: "Turkish", native_name: "Türkçe", code: "tr"
Language.create english_name: "Tsonga", native_name: "Xitsonga", code: "ts"
Language.create english_name: "Tatar", native_name: "татар теле, tatar tele", code: "tt"
Language.create english_name: "Twi", native_name: "Twi", code: "tw"
Language.create english_name: "Tahitian", native_name: "Reo Tahiti", code: "ty"
Language.create english_name: "Uighur, Uyghur", native_name: "Uyƣurqə, ئۇيغۇرچە‎", code: "ug"
Language.create english_name: "Ukrainian", native_name: "українська мова", code: "uk"
Language.create english_name: "Urdu", native_name: "اردو", code: "ur"
Language.create english_name: "Uzbek", native_name: "O'zbek, Ўзбек, أۇزبېك‎", code: "uz"
Language.create english_name: "Venda", native_name: "Tshivenḓa", code: "ve"
Language.create english_name: "Vietnamese", native_name: "Tiếng Việt", code: "vi"
Language.create english_name: "Volapük", native_name: "Volapük", code: "vo"
Language.create english_name: "Walloon", native_name: "walon", code: "wa"
Language.create english_name: "Welsh", native_name: "Cymraeg", code: "cy"
Language.create english_name: "Wolof", native_name: "Wollof", code: "wo"
Language.create english_name: "Western Frisian", native_name: "Frysk", code: "fy"
Language.create english_name: "Xhosa", native_name: "isiXhosa", code: "xh"
Language.create english_name: "Yiddish", native_name: "ייִדיש", code: "yi"
Language.create english_name: "Yoruba", native_name: "Yorùbá", code: "yo"
Language.create english_name: "Zhuang, Chuang", native_name: "Saɯ cueŋƅ, Saw cuengh", code: "za"
Language.create english_name: "Zulu", native_name: "isiZulu", code: "zu"

hindi = Language.find_by code: "hi"
russian = Language.find_by code: "ru"
english = Language.find_by code: "en"

f = Feedback.create comment: "Completes homework on time and with care", criteria: 'Homework', gender: 'neutral'
f.translations.create language_id: hindi.id, comment: "समय पर और देखभाल के साथ होमवर्क पूरा करत"
f.translations.create language_id: russian.id, comment: "Исполняет домашние задания в срок и с вниманием"
f.translations.create language_id: english.id, comment: "Completes homework on time and with care"

f = Feedback.create comment: "Notebook work is neat and organized", criteria: 'Homework', gender: 'neutral'
f.translations.create language_id: hindi.id, comment: "नोटबुक काम स्वच्छ और संगठित ह"
f.translations.create language_id: russian.id, comment: "Тетрадка в аккуратном состояние и хорошо организована"
f.translations.create language_id: english.id, comment: "Notebook work is neat and organized"

stephen = User.create first_name: "Mark", last_name: "Stephen", email: "aaron.romeo+mark@gmail.com", gender: "male",
            role: "parent", language_id: english.id, password: 'SWTOEDU2013'
roberts = User.create first_name: "June", last_name: "Roberts", email: "aaron.romeo+june@gmail.com", gender: "female",
            role: "parent", language_id: english.id, password: 'SWTOEDU2013'
amarman = User.create first_name: "Praak", last_name: "Amarman", email: "aaron.romeo+praak@gmail.com", gender: "male",
            role: "parent", language_id: hindi.id, password: 'SWTOEDU2013'
panpreet = User.create first_name: "Indira", last_name: "Panpreet", email: "aaron.romeo+akbal@gmail.com", gender: "female",
            role: "parent", language_id: hindi.id, password: 'SWTOEDU2013'
sharapova = User.create first_name: "Denis", last_name: "Sharapova", email: "aaron.romeo+denis@gmail.com", gender: "male",
            role: "parent", language_id: russian.id, password: 'SWTOEDU2013'
chicherova = User.create first_name: "Yevgeniya", last_name: "Chicherova", email: "aaron.romeo+yevgeniya@gmail.com", gender: "female",
            role: "parent", language_id: russian.id, password: 'SWTOEDU2013'

da = User.create first_name: "Tanya", last_name: "Da Silva", email: "aaron.romeo+tanya@gmail.com", gender: "female",
            role: "teacher", language_id: english.id, password: 'SWTOEDU2013'
ka = User.create first_name: "Ragini", last_name: "Kashkina", email: "aaron.romeo+ragini@gmail.com", gender: "female",
            role: "teacher", language_id: english.id, password: 'SWTOEDU2013'

sc_d = StudentClass.create name: "Grade 5 - Ms. Da Silva", teacher_id: da.id
Student.create first_name: "Mohandas", last_name: "Amarman", student_class_id: sc_d.id, parent_id: amarman.id, gender: "male"
Student.create first_name: "Sumeet", last_name: "Panpreet", student_class_id: sc_d.id, parent_id: panpreet.id, gender: "female"
Student.create first_name: "Anna", last_name: "Sharapova", student_class_id: sc_d.id, parent_id: sharapova.id, gender: "female"
Student.create first_name: "Yuri", last_name: "Chicherova", student_class_id: sc_d.id, parent_id: chicherova.id, gender: "male"
Student.create first_name: "Charlie", last_name: "Stephen", student_class_id: sc_d.id, parent_id: stephen.id, gender: "male"
Student.create first_name: "Ella", last_name: "Roberts", student_class_id: sc_d.id, parent_id: roberts.id, gender: "female"

sc_k = StudentClass.create name: "Grade 4 - Ms. Kashkina", teacher_id: ka.id
Student.create first_name: "Sonya", last_name: "Panpreet", student_class_id: sc_k.id, parent_id: panpreet.id, gender: "female"
Student.create first_name: "Maria", last_name: "Sharapova", student_class_id: sc_k.id, parent_id: sharapova.id, gender: "female"
Student.create first_name: "Steph", last_name: "Roberts", student_class_id: sc_k.id, parent_id: roberts.id, gender: "female"

